### ISSUE TITLE
Two types of tin?

### ISSUE THREAD

**Issue by enkidu-smith** [minetest-mods/moreores#22]
I have the latest git of minetest (441740e), minetest_game (c7d558c) and moreores (0842b4f). I have an issue where there appear to be two sorts of tin ores : "default:tin_lump" and "moreores:tin_lump". While the moreores versions go through a MV grinder successfully, the default versions do not and block the grinder.

As I see it there are three possibilities:
1) I've screwed something up.
2) This is expected behaviour with minetest, minetest_game and moreores.
3) It's a bug.

**Comment by Calinou** [comment]
There are two open pull requests for this, https://github.com/minetest-mods/moreores/pull/18 and https://github.com/minetest-mods/moreores/pull/20.

Neither of them seem to provide an alias to avoid breaking existing worlds, also, mods that rely on the More Ores tin will need to be updated in order to support the tin now found in minetest_game.

**Comment by enkidu-smith** [comment]
I'm unsure of the protocol here. Close and reference the pull requests??

**Comment by Calinou** [comment]
> I'm unsure of the protocol here. Close and reference the pull requests??

I'd currently favor https://github.com/minetest-mods/moreores/pull/18, but it does not include an alias for compatibility, so I asked the submitter why they did not add one (but I could add the alias myself, too).

Anyway, we have to choose one of these pull requests, we can't merge both.

**Comment by enkidu-smith** [comment]
OK. Thanks.

**Comment by enkidu-smith** [comment]
The fix solves the issue for me.
